image: gutenye/archlinux-drone
script:
  - echo 1
  #- [[ $(git show-ref $(git describe --abbrev=0 --tags)) == $(git rev-parse HEAD) ]] || exit 2

deploy:
  bash:
    script:
      - chown docker:docker -R misc/aur
      - su docker -c 'cd misc && ./build.sh aur'
