image: gutenye/archlinux-drone
script:
  - whoami
  - pwd
  - echo 1
  #- [[ $(git show-ref $(git describe --abbrev=0 --tags)) == $(git rev-parse HEAD) ]] || exit 2

deploy:
  bash:
    script:
      - cd misc && ./build.sh aur
